import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { mantraRimba, wolfer, utamAvo, utmAvoItalic } from "@/lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to Seedy",
  description: "Generated by create next app",
  icons: "/logo-seedy-mo-i-tra-ng-1.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mantraRimba.variable} ${wolfer.variable} ${utamAvo.variable} ${utmAvoItalic.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
